apiVersion: batch/v1
kind: Job
metadata:
  name: postgresql-job
spec:
  template:
    spec:
      containers:
        - name: migration
          image: postgres
          command: ["sh", "-c", "/home/docker/createdb.sh"]
          volumeMounts:
            - mountPath: /mnt/scripts
              name: dump-volume
              readOnly: false
      volumes:
        - name: dump-volume
          hostPath:
            path: /mnt/scripts
            type: Directory
      restartPolicy: Never
